import PlayStation from "@/public/images/header_playstation_image.webp";
import MacBook from "@/public/images/header_macbook_image.webp";
import SonyAirpods from "@/public/images/sony_airpods.webp";
import GarminWatch from "@/public/images/garmin_watch.webp";
import AppleAirPods from "@/public/images/apple_airpods.webp";
import BoseHeadset from "@/public/images/bose_headset.webp";
import SamsungProjector from "@/public/images/samsung_projector.webp";
import CanonCamera from "@/public/images/canon_camera.webp";
import AsusLaptop from "@/public/images/asus_laptop.webp";
import SamsungGalaxyMobile from "@/public/images/samsung_galaxy_mobile.webp";

export const productList = [
  {
    id: "1",
    image: BoseHeadset,
    title: "Bose QuietComfort 45",
    description: "The Bose QuietComfort 45 headphones offer world-class noise cancellation and premium sound quality.",
    rating: 4.5,
    discountPrice: 329.99,
    originalPrice: 399.99,
    brand: "Bose",
    color: "Black",
    category: "Headphone",
  },
  {
    id: "2",
    image: AsusLaptop,
    title: "ASUS ROG Zephyrus G16",
    description: "The ASUS ROG Zephyrus G16 is a powerful gaming laptop with cutting-edge graphics and performance.",
    rating: 5,
    discountPrice: 1999.99,
    originalPrice: 2199.99,
    brand: "ASUS",
    color: "Grey",
    category: "Laptop",
  },
  {
    id: "3",
    image: SamsungGalaxyMobile,
    title: "Samsung Galaxy S23",
    description: "The Samsung Galaxy S23 offers an exceptional camera and powerful processor in a sleek design.",
    rating: 4.5,
    discountPrice: 799.99,
    originalPrice: 899.99,
    brand: "Samsung",
    color: "Pink",
    category: "Smartphone",
  },
  {
    id: "4",
    image: PlayStation,
    title: "PlayStation 5",
    description: "The PlayStation 5 takes gaming to the next level with blazing-fast load times and stunning visuals.",
    rating: 4.5,
    discountPrice: 499.99,
    originalPrice: 549.99,
    brand: "Sony",
    color: "White",
    category: "Console",
  },
  {
    id: "5",
    image: MacBook,
    title: "MacBook Pro 16",
    description: "The MacBook Pro 16, powered by Apple silicon, delivers unmatched performance for creators.",
    rating: 4.5,
    discountPrice: 2499.99,
    originalPrice: 2699.99,
    brand: "Apple",
    color: "Silver",
    category: "Laptop",
  },
  {
    id: "6",
    image: GarminWatch,
    title: "Garmin Venu 2",
    description: "The Garmin Venu 2 smartwatch blends fitness tracking with advanced health insights.",
    rating: 4.5,
    discountPrice: 349.99,
    originalPrice: 399.99,
    brand: "Garmin",
    color: "Black",
    category: "Smartwatch",
  },
  {
    id: "7",
    image: CanonCamera,
    title: "Canon EOS R5",
    description: "The Canon EOS R5 is a game-changing mirrorless camera with 8K video recording and superior autofocus.",
    rating: 4.5,
    discountPrice: 3899.99,
    originalPrice: 4199.99,
    brand: "Canon",
    color: "Black",
    category: "Camera",
  },
  {
    id: "8",
    image: AppleAirPods,
    title: "Apple AirPods Pro 2nd gen",
    description: "Apple AirPods Pro (2nd Gen) with MagSafe offer improved noise cancellation and spatial audio.",
    rating: 4.5,
    discountPrice: 399.99,
    originalPrice: 449.99,
    brand: "Apple",
    color: "White",
    category: "Earbuds",
  },
  {
    id: "9",
    image: SonyAirpods,
    title: "Sony WF-1000XM5",
    description: "Sony WF-1000XM5 true wireless earbuds provide exceptional sound and class-leading noise cancellation.",
    rating: 4.5,
    discountPrice: 299.99,
    originalPrice: 349.99,
    brand: "Sony",
    color: "Black",
    category: "Earbuds",
  },
  {
    id: "10",
    image: SamsungProjector,
    title: "Samsung Projector 4k",
    description: "The Samsung 4K Projector offers an immersive cinematic experience with vibrant picture quality.",
    rating: 4.5,
    discountPrice: 1499.99,
    originalPrice: 1699.99,
    brand: "Samsung",
    color: "White",
    category: "Projector",
  },
];
